version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  frontend:
    build: 
      context: ./frontend
    container_name: nsd_frontend
    volumes:
      - frontend:/app/build
    ports:
      - 80:80

  backend:
    build: ./backend
    container_name: nsd_backend
    command: gunicorn nsd.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  postgres_data:
  backend:
  frontend: